#!/usr/bin/env sh
# Minimal Gradle wrapper launcher for Octa Code (M0).
# Requires gradle/wrapper/gradle-wrapper.jar (generated by `gradle wrapper`
# on first open in Android Studio / AndroidIDE if absent).
APP_BASE_NAME=$(basename "$0")
APP_HOME=$(cd "$(dirname "$0")" >/dev/null && pwd)
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
if [ ! -f "$CLASSPATH" ]; then
  echo "gradle-wrapper.jar not found. Open the project once in Android Studio/AndroidIDE" >&2
  echo "or run 'gradle wrapper --gradle-version 8.7' to generate it." >&2
  exit 1
fi
exec java -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
